site_name: Camera Kit Docs

theme:
  name: "readthedocs"

#  features:
#    - navigation.path

plugins:
  - mkdocstrings

nav:
  - Camera Kit Docs: index.md
  - Tutorials: tutorials.md
  - How-To-Guides: how-to-guides.md
  - References: reference.md
  - Explanations: explanation.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
